Metrics/LineLength:
  Max: 91

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/mail/notify.rb'
    - 'lib/mail/notify/delivery_method.rb'
    - 'lib/mail/notify/railtie.rb'